-- Migration neutralisée : la table "Announcement" n'existe plus dans le schéma actuel.
-- Cette migration est maintenue comme no-op pour permettre la reconstruction de la shadow DB.
-- Historique conservé mais aucune opération de schema n'est rejouée ici.
