-- Ajout des colonnes de ventilation sur Reservation
ALTER TABLE IF EXISTS "Reservation"
  ADD COLUMN IF NOT EXISTS "stripeFeeCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "edgemyFeeCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "serviceFeeCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "coachNetCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "isPackage" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "sessionsCount" INTEGER;

-- Ajout des colonnes de ventilation sur CoachingPackage
ALTER TABLE IF EXISTS "CoachingPackage"
  ADD COLUMN IF NOT EXISTS "stripeFeeCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "edgemyFeeCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "serviceFeeCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "coachNetCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sessionPayoutCents" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sessionsCompletedCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "sessionsTotalCount" INTEGER NOT NULL DEFAULT 0;
